---
title: "move_times"
output: html_document
date: "2024-04-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analysis script for "

```{r load libraries}
library(readr)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(stats)
library(lme4)
library(dplyr)
library(ez)
library(ltm)
library(interactions)
```


## Extract dataframe from csv file and get (mean, sd) or (mean, se) summary

```{r read csv}

setwd("C:/Users/micha/OneDrive/My_GitHub_Repos/AutonomyFitts/data/")
task_df <- read_csv("all_data.csv")

auto_levels_order <- c("low_auto", "med_auto", "high_auto")  # Replace these with your actual level names
fitts_id_levels_order <- c("low_fitts_id", "med_fitts_id2", "med_fitts_id1", "high_fitts_id")  # Replace these with your actual level names

# Reorder the factor levels of "auto_level" according to levels_order
task_df$auto_level <- factor(task_df$auto_level, levels = auto_levels_order)

# Reorder the factor levels of "fitts_id_level" according to levels_order
task_df$fitts_id_level <- factor(task_df$fitts_id_level, levels = fitts_id_levels_order)


######################### get mean and sd (or se) ######################### 
task_df %>%
  group_by(auto_level, ring_id) %>%
  get_summary_stats(mdmt_ave, type = "mean_sd")



```

## Plots

```{r do plotting}


mdmt_dim_df <- data.frame(task_df$mdmt_reliable, task_df$mdmt_predictable, task_df$mdmt_consistent, task_df$mdmt_counton,task_df$mdmt_capable, task_df$mdmt_skilled, task_df$mdmt_competent, task_df$mdmt_meticulous)

######################### calculate Cronbach's Alpha with 95% confidence interval ######################### 
cronbach.alpha(mdmt_dim_df, CI=TRUE)



bxp1 <- ggboxplot(
  task_df, x = "fitts_id_level", y = "mdmt_ave",
  color = "auto_level", palette = "jco"
  )
bxp1


```


## Check assumptions

```{r check assumptions}

######################### check for outliers ######################### 
task_df %>%
  group_by(auto_level, ring_id) %>%
  identify_outliers(mdmt_ave)

######################### check normality ######################### 
task_df %>%
  group_by(auto_level, ring_id) %>%
  shapiro_test(mdmt_ave)

######################### plot normality ######################### 
ggqqplot(task_df, "mdmt_ave", ggtheme = theme_bw()) +
  facet_grid(ring_id ~ auto_level, labeller = "label_both")


```


## Fit Model

```{r fit model}

######################### Two-way mixed ANOVA test #########################  
res.aov <- anova_test(
  data = task_df, dv = mdmt_ave, wid = part_id,
  within = c(auto_level, fitts_id_level)
  )
get_anova_table(res.aov)


# #################### Effect of auto_level for each ring_id #################### 
# one.way <- task_df %>%
#   group_by(ring_id) %>%
#   anova_test(dv = mdmt_ave, wid = part_id, within = auto_level) %>%
#   get_anova_table() %>%
#   adjust_pvalue(method = "bonferroni")
# one.way
# 
# #################### Effect of ring_id for each auto_level #################### 
# one.way <- task_df %>%
#   group_by(auto_level) %>%
#   anova_test(dv = mdmt_ave, wid = part_id, within = ring_id) %>%
#   get_anova_table() %>%
#   adjust_pvalue(method = "bonferroni")
# one.way


#################### Pairwise comparisons between auto_level groups for each ring_id #################### 
pwc1 <- task_df %>%
  group_by(fitts_id_level) %>%
  pairwise_t_test(
    mdmt_ave ~ auto_level, paired = TRUE,
    p.adjust.method = "holm"
    )
pwc1
# Create a box plot
pwc1 <- pwc1 %>% add_xy_position(x = "auto_level", group = "fitts_id_level")
bxp2 <- ggboxplot(
  task_df, x = "auto_level", y = "mdmt_ave", 
  color = "fitts_id_level", palette = "jco"
) +
  stat_pvalue_manual(
    pwc1, color = "fitts_id_level", group.by = "legend.var",
    bracket.nudge.y = 0.2, step.increase = 0.15, label.size = 3, vjust = 0.1,
    tip.length = 0, y.position = 20
  )
bxp2


#################### Pairwise comparisons between ring_id groups for each auto_level #################### 
pwc2 <- task_df %>%
  group_by(auto_level) %>%
  pairwise_t_test(
    mdmt_ave ~ fitts_id_level, paired = TRUE,
    p.adjust.method = "holm"
    )
pwc2
# Create a box plot
pwc2 <- pwc2 %>% add_xy_position(x = "fitts_id_level", group = "auto_level")
bxp3 <- ggboxplot(
  task_df, x = "fitts_id_level", y = "mdmt_ave", 
  color = "auto_level", palette = "jco"
) +
  stat_pvalue_manual(
    pwc2, color = "auto_level", group.by = "legend.var",
    bracket.nudge.y = 0.2, step.increase = 0.5, label.size = 3, vjust = 0.1,
    tip.length = 0, y.position = 20
  )
bxp3


```

## Plot with pairwise

```{r fit model}

new_auto_levels_order <- c("none", "med", "high")  # Replace these with your actual level names
new_fitts_id_levels_order <- c("1", "2", "3", "4")  # Replace these with your actual level names

# Reorder the factor levels of "auto_level" according to levels_order
task_df$Autonomy <- factor(task_df$Autonomy, levels = new_auto_levels_order)

# Reorder the factor levels of "fitts_id_level" according to levels_order
task_df$Difficulty <- factor(task_df$Difficulty, levels = new_fitts_id_levels_order)

#################### Pairwise comparisons between ring_id groups for each auto_level #################### 
pwc2 <- task_df %>%
  group_by(Autonomy) %>%
  pairwise_t_test(
    mdmt_ave ~ Difficulty, paired = TRUE,
    p.adjust.method = "holm"
    )
# Create a box plot
pwc2 <- pwc2 %>% add_xy_position(x = "Difficulty", group = "Autonomy")
bxp3 <- ggboxplot(
  task_df, x = "Difficulty", y = "mdmt_ave", 
  fill = "Autonomy", palette = c("#00AFBB", "#E7B800", "#FC4E07"),
  xlab = "Ring No.", ylab = "Averaged MDMT"
) +
  stat_pvalue_manual(
    pwc2, group.by = "legend.var", hide.ns = TRUE,
    bracket.nudge.y = -0.1, step.increase = 0.05, label.size = 4, vjust = 0.7,
    tip.length = 0.02, y.position = 9.5, color = "Autonomy"
  )
bxp3

ggsave(file="mdmt_average.pdf", plot=bxp3, width=5, height=5)


```



## Fit Linear Model

```{r fit model}

# ###### fit linear mixed model 1 ######
model <- lmer(mdmt_ave ~ auto_num * fitts_id_num + (1+auto_num|part_id) + (1+fitts_id_num|part_id) + (1|part_id),
              data = task_df)
summary(model)


###### fit linear mixed model 2 ######
fit <- lm(mdmt_ave ~ fitts_id_num * auto_level, data = task_df)
# summary(fit)

interact_plot(fit, pred = fitts_id_num, modx = auto_level, 
              interval = TRUE, int.type = "confidence", int.width = .8,
              plot.points = TRUE,
              x.label="Fitts ID", y.label="MDMT Averaged", 
              modx.labels = c("low", "med", "high")
              )


```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
