---
title: "p_trust"
output: html_document
date: "2023-09-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analysis script for "

```{r load libraries}
library(readr)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(stats)
library(lme4)
library(dplyr)
library(ez)
library(ltm)
library(interactions)
library(lmerTest)
```


## Extract dataframe from csv file and get (mean, sd) or (mean, se) summary

```{r read csv}

setwd("C:/Users/micha/OneDrive/My_GitHub_Repos/AutonomyFitts/data/")
task_df <- read_csv("all_data.csv")


auto_levels_order <- c("low_auto", "med_auto", "high_auto")  # Replace these with your actual level names
fitts_id_levels_order <- c("low_fitts_id", "med_fitts_id1", "med_fitts_id2", "high_fitts_id")  # Replace these with your actual level names

# Reorder the factor levels of "auto_level" according to levels_order
task_df$auto_level <- factor(task_df$auto_level, levels = auto_levels_order)

# Reorder the factor levels of "fitts_id_level" according to levels_order
task_df$fitts_id_level <- factor(task_df$fitts_id_level, levels = fitts_id_levels_order)

```

# scatterplot and save, and compute correlation
```{r correlation}

######################### scatterplot ######################### 
p <- ggscatter(task_df, x = "mdmt_ave", y = "single_trust",
          add = "reg.line",                                 # Add regression line
          conf.int = TRUE,                                  # Add confidence interval
          add.params = list(color = "blue",
                            fill = "lightgray"),
          xlab = "Averaged MDMT", ylab = "Single-Scale Trust"
          ) 
      # + theme(plot.title = element_text(size = 15, face = "bold"),
      #   axis.title.x = element_text(size = 28, face = "bold"),
      #   axis.title.y = element_text(size = 28, face = "bold"),
      #   axis.text = element_text(size = 24),
      #   legend.title = element_text(size = 28),
      #   legend.text = element_text(size = 28),
      #   legend.position= "none")
  # stat_cor(method = "pearson", label.x = 1.5, label.y = 7.5)  # Add correlation coefficient
p
# ggsave(file="pdfs/perf_trust_corr.pdf", plot=p, width=10, height=6)



# ######################### scatterplot ######################### 
# ggscatter(task_df, x = "traj_err", y = "p_trust",
#           add = "reg.line",                                 # Add regression line
#           conf.int = TRUE,                                  # Add confidence interval
#           add.params = list(color = "blue",
#                             fill = "lightgray"),
#           xlab = "Trajectory Tracking Error", ylab = "Single-Scale Trust"
#           )+
#   stat_cor(method = "pearson", label.x = 1, label.y = 7.5)  # Add correlation coefficient


######################### correlation test ######################### 
res <- cor.test(task_df$mdmt_ave, task_df$single_trust, 
                    method = "pearson")
res


```


## Fit Linear Model

```{r fit model}

###### fit linear mixed model 1 ######
model <- lmer(single_trust ~ mdmt_ave * auto_num + (1 | part_id),
              data = task_df)
summary(model)

# anova(model)
# interact_plot(model, pred = fitts_id_num, modx = auto_num, interval = TRUE, int.width = 0.8)
# interact_plot(model, pred = fitts_id_num, modx = auto_num, plot.points = TRUE, interval = TRUE, int.width = 0.8)
# interact_plot(model, pred = auto_num, modx = fitts_id_num, interval = TRUE, int.width = 0.8)


###### fit linear mixed model 2 ######
fit <- lm(single_trust ~ mdmt_ave * auto_level, data = task_df)
# summary(fit)
interact_plot(fit, pred = mdmt_ave, modx = auto_level, 
              interval = TRUE, int.type = "confidence", int.width = .8,
              plot.points = TRUE,
              x.label="Averaged MDMT", y.label="Single-Scale Trust", 
              modx.labels = c("low", "med", "high")
              )


###### fit linear mixed model 3 ######
fit3 <- lm(single_trust ~ mdmt_ave * fitts_id_level, data = task_df)
# summary(fit)
interact_plot(fit3, pred = mdmt_ave, modx = fitts_id_level, 
              interval = TRUE, int.type = "confidence", int.width = .8,
              plot.points = TRUE,
              x.label="Averaged MDMT", y.label="Single-Scale Trust", 
              modx.labels = c("low", "med1", "med2", "high")
              )


###### correlation by autonomy group ######
correlation_by_group <- task_df %>%
  group_by(auto_level) %>%
  summarise(correlation = cor(single_trust, mdmt_ave))

print(correlation_by_group)


```

## Fit Linear Model

```{r fit model}

###### fit linear mixed model 1 ######
model <- lmer(single_trust ~ mdmt_ave * fitts_id_num + (1 | part_id),
              data = task_df)
summary(model)

# anova(model)
# interact_plot(model, pred = fitts_id_num, modx = auto_num, interval = TRUE, int.width = 0.8)
# interact_plot(model, pred = fitts_id_num, modx = auto_num, plot.points = TRUE, interval = TRUE, int.width = 0.8)
# interact_plot(model, pred = auto_num, modx = fitts_id_num, interval = TRUE, int.width = 0.8)


###### correlation by autonomy group ######
correlation_by_group <- task_df %>%
  group_by(fitts_id_level) %>%
  summarise(correlation = cor(single_trust, mdmt_ave))

print(correlation_by_group)


```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
