---
title: "move_times"
output: html_document
date: "2024-04-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analysis script for "

```{r load libraries}
library(readr)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(stats)
library(lme4)
library(dplyr)
library(ez)
library(ltm)
library(interactions)
```


## Extract dataframe from csv file and get (mean, sd) or (mean, se) summary

```{r read csv}

setwd("C:/Users/micha/OneDrive/My_GitHub_Repos/AutonomyFitts/data/")
task_df <- read_csv("all_data.csv")

auto_levels_order <- c("low_auto", "med_auto", "high_auto")  # Replace these with your actual level names
fitts_id_levels_order <- c("low_fitts_id", "med_fitts_id2", "med_fitts_id1", "high_fitts_id")  # Replace these with your actual level names

# Reorder the factor levels of "auto_level" according to levels_order
task_df$auto_level <- factor(task_df$auto_level, levels = auto_levels_order)

# Reorder the factor levels of "fitts_id_level" according to levels_order
task_df$fitts_id_level <- factor(task_df$fitts_id_level, levels = fitts_id_levels_order)


######################### get mean and sd (or se) ######################### 
task_df %>%
  group_by(auto_level, ring_id) %>%
  get_summary_stats(tlx_ave, type = "mean_sd")



```

## Plots

```{r do plotting}

task_df$tlx_successful <- 21 - task_df$tlx_successful

tlx_dims_df <- data.frame(task_df$tlx_mental, task_df$tlx_physical, task_df$tlx_hurried, 
                          task_df$tlx_insecure, task_df$tlx_hard, task_df$tlx_successful)

######################### calculate Cronbach's Alpha with 95% confidence interval ######################### 
cronbach.alpha(tlx_dims_df, CI=TRUE)


```

## Plots

```{r one-off consistency analyses}

###### remove mental ######
tlx_dims_df <- data.frame(task_df$tlx_physical, task_df$tlx_hurried, 
                          task_df$tlx_insecure, task_df$tlx_hard, task_df$tlx_successful)
cronbach.alpha(tlx_dims_df, CI=TRUE)


###### remove physical ######
tlx_dims_df <- data.frame(task_df$tlx_mental, task_df$tlx_hurried, 
                          task_df$tlx_insecure, task_df$tlx_hard, task_df$tlx_successful)
cronbach.alpha(tlx_dims_df, CI=TRUE)


###### remove hurried ######
tlx_dims_df <- data.frame(task_df$tlx_mental, task_df$tlx_physical, 
                          task_df$tlx_insecure, task_df$tlx_hard, task_df$tlx_successful)
cronbach.alpha(tlx_dims_df, CI=TRUE)


###### remove insecure ######
tlx_dims_df <- data.frame(task_df$tlx_mental, task_df$tlx_physical, task_df$tlx_hurried, 
                          task_df$tlx_hard, task_df$tlx_successful)
cronbach.alpha(tlx_dims_df, CI=TRUE)


###### remove how hard ######
tlx_dims_df <- data.frame(task_df$tlx_mental, task_df$tlx_physical, task_df$tlx_hurried, 
                          task_df$tlx_insecure, task_df$tlx_successful)
cronbach.alpha(tlx_dims_df, CI=TRUE)


###### remove successful ######
tlx_dims_df <- data.frame(task_df$tlx_mental, task_df$tlx_physical, task_df$tlx_hurried, 
                          task_df$tlx_insecure, task_df$tlx_hard)
cronbach.alpha(tlx_dims_df, CI=TRUE)


```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
